import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import { HeaderProvider, HeaderActions } from '@/components/HeaderContext';
import { ChefHat } from 'lucide-react';
import Link from 'next/link';
import "./globals.css";
import React from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "MealPlan Pro",
    description: "Generated by Alessandro Crescenzi",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="it">
      <body className="bg-gray-50 min-h-screen">
        <HeaderProvider>
          <header className="bg-white shadow">
            <div className="max-w-7xl mx-auto px-4 py-6 flex justify-between items-center">
              <Link href="/" className="text-3xl font-bold text-gray-900 flex items-center gap-2 hover:text-green-800 transition-colors">
                <ChefHat className="text-green-600" />
                MealPlan Pro
              </Link>
              <HeaderActions />
            </div>
          </header>
          <main className="max-w-7xl mx-auto px-4 py-8">
            {children}
          </main>
        </HeaderProvider>
      </body>
    </html>
  );
}
