import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {ChefHat, Edit2, Plus, RotateCcw} from 'lucide-react';
import Link from 'next/link';
import "./globals.css";
import React from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="it">
        <body className="bg-gray-50 min-h-screen">
        <header className="bg-white shadow">
            <div className="max-w-7xl mx-auto px-4 py-6">
                <div className="flex items-center justify-between">
                    <Link href="/"
                          className="text-3xl font-bold text-gray-900 flex items-center gap-2 hover:text-green-800 transition-colors">
                        <ChefHat className="text-green-600"/>
                        MealPlan Pro
                    </Link>
                </div>
            </div>
        </header>

        <main className="max-w-7xl mx-auto px-4 py-8">
            {children} {/* qui verrà iniettato il contenuto della pagina */}
        </main>
        </body>
        </html>
    );
}
